### PR TITLE
(Not a PR!)

### PR DESCRIPTION
**Pull request by fox8091**
I have to do this due to issues not being open. Regardless, JUNKNUM shouldn't be needed. There is no need to pad the CXI if injected properly, and is actually bad behavior.

### CODE REVIEW

**Comment by Reisyukaku** [comment]
So as long as it's smaller it'll work? or does that mean i need to edit the ncch info? if the latter, thats too much work lol.

**Comment by fox8091** [comment]
No, the way you inject it is the important part. Not the CXI. Padding it is a bad idea. I hate to bring this up, knowing what your reaction will be, but look at Luma. The way Luma does it allows for any size, bigger or smaller.

**Comment by Reisyukaku** [comment]
Not to sound mean but this is a pain to follow.. its all over the place lol.. just give me the gist.

**Comment by AuroraWright** [comment]
- Find the loader cxi, this is done best by parsing section0, by increasing the pointer of the size of each cxi until the app name in the cxi starts with "load". Once found, also save loader's size. https://github.com/AuroraWright/Luma3DS/blob/master/source/patches.c#L85
- 3 memcpys:
  - start of section 0 -> section 0 destination (until loader)
  - 3ds injector -> section 0 dest (just after the first memcpy)
  - section 0 after loader -> section 0 dest (just after the second memcpy)  
    https://github.com/AuroraWright/Luma3DS/blob/master/source/firm.c#L383

**Comment by Reisyukaku** [comment]
@AuroraWright Oh, so basically you're copying the arm11 service cxis, splitting them (ommitting loader) and sticking the new size loader in there? I thought about doing that once, but doesnt it mess with offsets of other things? it'd change the 'section 0' size at least

**Comment by AuroraWright** [comment]
Since you copy section 0 earlier, it doesn't really matter if the size changed (of course after you do this you have to skip section0 from the final memcpys). It's copied in parts to the section 0 destination, first all the cxis before loader, then the new loader, then all the other cxis after loader.

**Comment by AuroraWright** [comment]
As for the offsets: there's no offset to be respected in section0, just a bunch of cxis one after the other, (I think the bootloader does kind of the same parsing we do to find loader) so enlarging/shrinking the section has no negative effects

**Comment by TuxSH** [comment]
^ You just have a memory (FCRAM) limitation on O3DS, but that's pretty much all.

**Pull request closed without merging**
